import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BooksTemplate from '../templates/books/index';
import { MainContainer, TitleHome } from './styles'

const Home: NextPage = () => {
  return (
    <MainContainer >
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TitleHome className={styles.title}>
        Books!
      </TitleHome>
      <main className={styles.main}>
       <BooksTemplate/>
      </main>
    </MainContainer>
  )
}

export default Home
